"""step_4_execution_learning

Revision ID: 219c0291b5f3
Revises: 5844a01a9fc9
Create Date: 2026-10-08 01:10:11.465614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '219c0291b5f3'
down_revision: Union[str, Sequence[str], None] = '5844a01a9fc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_calibrations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=True),
    sa.Column('action_type', sa.String(), nullable=True),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('calibration_factor', sa.Float(), nullable=True),
    sa.Column('bias', sa.Float(), nullable=True),
    sa.Column('historical_prediction_error', sa.Float(), nullable=True),
    sa.Column('number_of_observations', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_learning_calibrations_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_learning_calibrations'))
    )
    with op.batch_alter_table('actions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('execution_details_json', sa.Text(), nullable=True))

    with op.batch_alter_table('decision_memory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('recommendation_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('expected_impact_json', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('actual_impact_json', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('variance_json', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('outcome_classification', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('confidence', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('learning_signal', sa.Text(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_decision_memory_recommendation_id_recommendations'), 'recommendations', ['recommendation_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_decision_memory_organization_id_organizations'), 'organizations', ['organization_id'], ['id'])
        batch_op.drop_column('result')

    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('actual_profit', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('variance', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('outcome_status', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('evaluated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.drop_column('evaluated_at')
        batch_op.drop_column('outcome_status')
        batch_op.drop_column('variance')
        batch_op.drop_column('actual_profit')

    with op.batch_alter_table('decision_memory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('result', sa.VARCHAR(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_decision_memory_organization_id_organizations'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_decision_memory_recommendation_id_recommendations'), type_='foreignkey')
        batch_op.drop_column('learning_signal')
        batch_op.drop_column('confidence')
        batch_op.drop_column('outcome_classification')
        batch_op.drop_column('variance_json')
        batch_op.drop_column('actual_impact_json')
        batch_op.drop_column('expected_impact_json')
        batch_op.drop_column('recommendation_id')
        batch_op.drop_column('organization_id')

    with op.batch_alter_table('actions', schema=None) as batch_op:
        batch_op.drop_column('execution_details_json')

    op.drop_table('learning_calibrations')
    # ### end Alembic commands ###
